### ISSUE TITLE
字幕會顯示錯誤的時間

### ISSUE THREAD

**Issue by WingCH** [Makememo/MemoAI#257]
**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/19588517/af42ead3-2376-447e-8853-30dcf3a81ff2)

**Desktop (please complete the following information):**
 - OS: Window 11
 - Model: Largev2
 - Version: 1.3.0

**Additional context**

**Comment by sdugoten** [comment]
same issue using v1.3.0

**Comment by sdugoten** [comment]
You can use this to reproduce

[https://www.youtube.com/watch?v=CmFIcAn0PeQ](url)

![image](https://github.com/Makememo/MemoAI/assets/7108552/a2c92d85-7955-49bd-bc26-d5046ad83b60)


The problem is that when the original line is long, the translation might drop to the next slot...which make the whole translation slip

**Comment by joyshan1986** [comment]
version 1.3.2 still having this problem for video over 40 minutes

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.3 

1. When transcribing, select cuda mode for GPU mode
2. Go to Settings-Lab-Turn on the flash attention mechanism switch

1. 轉寫時，GPU 模式選擇 cuda 模式
2. 前往設置 - 實驗室 - 打開 flash attention 機制開關

**Comment by sdugoten** [comment]
> https://github.com/Makememo/MemoAI/releases/tag/v1.3.3
> 
> * When transcribing, select cuda mode for GPU mode
> * Go to Settings-Lab-Turn on the flash attention mechanism switch
>   --
> * 轉寫時，GPU 模式選擇 cuda 模式
> * 前往設置 - 實驗室 - 打開 flash attention 機制開關

I just tested the provided sample  https://www.youtube.com/watch?v=CmFIcAn0PeQ  and the translation is off from the begining

![20240528_220143](https://github.com/Makememo/MemoAI/assets/7108552/46dedb2f-f052-4fb5-b8b6-09db88bfc746)

![20240528_220129](https://github.com/Makememo/MemoAI/assets/7108552/8b6c7f87-eb31-4f8a-9b33-a35b691043a5)
![20240528_220112](https://github.com/Makememo/MemoAI/assets/7108552/32daea60-9213-4757-bc62-603c2ce31c81)

The problem seems like missing translation on the red square above and everything slip

**Comment by sdugoten** [comment]
And then I tried to use Large(v3) to test again and translate, something wierd happen.  You see the translation all group into 1 line...
![20240528_222004](https://github.com/Makememo/MemoAI/assets/7108552/c5374eb2-b5e8-43dd-8860-93384d01b951)

**Comment by sdugoten** [comment]
![20240528_223136](https://github.com/Makememo/MemoAI/assets/7108552/230d398f-037f-4b03-9e7a-cbbd185533b1)

I understand you group a couple lines together for translation to save cost, which make sense.  I think you might try to do something in your coding like the picture above and see if you can mark the number for each line a bit more accurate

**Comment by sdugoten** [comment]
BTW, please reopen this case, I am pretty sure this is not fixed yet after a couple tries

@Makememo

**Comment by Makememo** [comment]
> BTW, please reopen this case, I am pretty sure this is not fixed yet after a couple tries
> 
> 
> 
> @Makememo 

His problem is a transliteration problem. The problem of your translation misalignment is an AI problem, and frankly there is no 100% solution, we tried your way, JSON output, and various methods. Did not have the desired effect. So we provide single sentences and continued translation to alleviate this dislocation.
