### ISSUE TITLE
VirusTotal detected W32.AIDetectMalware in v1.4.0

### ISSUE THREAD

**Issue by candideu** [Makememo/MemoAI#322]
Hi! I ran the MemoAI Windows .exe through VirusTotal, and 1/62 security vendors detected malware.

https://www.virustotal.com/gui/file/7d5c7ff515104c80ab3347f8c50972d439203df30e1de2899b58863e3faae3fd

https://virusscan.jotti.org/en-US/filescanjob/7c0q0jpluz

Do you know why that is?

**Comment by Makememo** [comment]
Then let's take a look. Thank you all for your feedback. It seems that Memo has to get a paid signature so that it won't be flagged as malware by antivirus software.

**Comment by Makememo** [comment]
We suspect that there is an issue with the Whisper open-source project. We'll recheck where the problem lies in the code. Additionally, since we don't have a signature, it may also be reported as containing malware.

However, I can assure you that Memo will not attack your device. Please feel free to use it.

**Comment by Makememo** [comment]
https://www.virustotal.com/gui/file/7d5c7ff515104c80ab3347f8c50972d439203df30e1de2899b58863e3faae3fd

To synchronize the progress, we tested it ourselves. This should be misinformation. There are many similar cases on the internet. And we'll add document hash validation to strengthen software security.
