### ISSUE TITLE
Why can't YouTube video be loaded

### ISSUE THREAD

**Issue by Makememo** [Makememo/MemoAI#73]
1. Make sure it's behind the link? A link like XXX = yyy, Please clean it up.
2. Chinese users need to use the agent, set to open the system agent
3. The wrong link was pasted

**Comment by duronxx** [comment]
Is there a discrepancy in module versions? With the same API key in the chat box, the Turbo-3.5-16k model works fine, but when a date is added, it doesn't work. Which version is set as the default in your settings? How can I roll back to the open version without having to download and update everything? This situation is quite unfortunate. I suggest allowing users to input the desired version instead of having it fixed. Thank you.[image](https://github.com/Makememo/MemoAI/assets/33643555/88476823-d826-47cc-99d9-1e7ec3b1663f)
![image](https://github.com/Makememo/MemoAI/assets/33643555/fde1a8d5-77d3-4cdc-91c3-1f8010bc003f)

**Comment by Makememo** [comment]
Thanks for the feedback, will soon support.
